import { empty } from "@prisma/client/runtime"
import {
  AlertTriangle,
  ArrowRight,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  Database,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  SunMedium,
  Trash,
  User,
  X,
  Plug,
  ChevronDown,
  FolderOpen,
  Settings,
  type Icon as LucideIcon,
  Table,
  MoreHorizontal,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  table: Table,
  logo: Database,
  close: X,
  spinner: Loader2,
  plug: Plug,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  empty: FolderOpen,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreHorizontal,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: CheckCircle,
}
